version: "3.9"

services:

  calisim:
    image: ghcr.io/plant-food-research-open/calisim-examples-workshop:${CALISIM_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: date -u +'%Y-%m-%dT%H:%M:%SZ'
        CALISIM_VERSION: ${CALISIM_VERSION:-latest}
      tags:
        - ghcr.io/plant-food-research-open/calisim-examples-workshop:latest
    ports:
      - 8888:8888
    volumes:
      - ./workshop:/workspace/workshop
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root